from __future__ import annotations

import json
from typing import Any

from app.node.core.base import BaseNode
from app.sandbox.docker_sandbox import DockerSandbox
from app.workflow.services.datasets import (
    compact_dataset_ref,
    compact_value_for_transport,
    is_dataset_ref,
    build_tabular_node_result,
)
from deepeye.workflows.models import Node, Port
from deepeye.workflows.registry import NodeSpec


class PythonCodeHandler:
    def __init__(self, sandbox: DockerSandbox | None) -> None:
        self.sandbox = sandbox

    def _ensure_sandbox(self) -> DockerSandbox:
        if not self.sandbox or not getattr(self.sandbox, "container", None):
            raise RuntimeError("Sandbox not available for python.code node")
        return self.sandbox

    def _resolve_code(self, node: Node) -> str:
        code = node.params.get("code")
        if not code:
            raise ValueError("code is required")
        return str(code)

    def _helper_prelude(self) -> str:
        # Standard dataset helpers reduce brittle format-specific code generated by the planner.
        return """
from datetime import date, datetime, time
from pathlib import Path
import json
import sys
import pandas as pd

def load_dataset_ref(ref):
    if isinstance(ref, list):
        refs = [item for item in ref if isinstance(item, dict)]
        if len(refs) != 1:
            raise ValueError("load_dataset_ref expects exactly one dataset_ref; use load_dataset_refs(data) for multiple inputs")
        ref = refs[0]
    if not isinstance(ref, dict):
        raise ValueError("dataset_ref must be an object")
    path = ref.get("path")
    if not path:
        raise ValueError("dataset_ref.path is required")
    fmt = str(ref.get("format") or Path(str(path)).suffix.lstrip(".")).lower()
    if fmt == "csv":
        return pd.read_csv(path)
    if fmt == "jsonl":
        return pd.read_json(path, lines=True)
    if fmt == "json":
        try:
            return pd.read_json(path, lines=True)
        except ValueError:
            return pd.read_json(path)
    if fmt in ("xlsx", "xls"):
        return pd.read_excel(path)
    if fmt == "parquet":
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported dataset_ref format: {fmt}")

def load_dataset_refs(data):
    return [load_dataset_ref(ref) for ref in data.get("dataset_ref", [])]

def emit_dataframe(df):
    print(df.to_json(orient="records"))

def _json_default(value):
    if value is pd.NaT or value is pd.NA:
        return None
    if isinstance(value, (pd.Timestamp, datetime, date, time)):
        return value.isoformat()
    item = getattr(value, "item", None)
    if callable(item):
        try:
            return item()
        except Exception:
            pass
    tolist = getattr(value, "tolist", None)
    if callable(tolist):
        try:
            return tolist()
        except Exception:
            pass
    try:
        if pd.isna(value):
            return None
    except Exception:
        pass
    return str(value)

def emit_json(value):
    print(json.dumps(value, ensure_ascii=False, default=_json_default))
""".strip()

    def _normalize_dataset_refs(self, value: Any) -> list[dict[str, Any]]:
        if is_dataset_ref(value):
            return [value]
        if isinstance(value, list):
            return [item for item in value if is_dataset_ref(item)]
        return []

    def _build_input_payload(self, node: Node, inputs: dict[str, Any]) -> dict[str, Any] | None:
        payload: dict[str, Any] = {}

        raw_input = inputs.get("input")
        if raw_input not in (None, "", [], {}):
            payload["input"] = compact_value_for_transport(raw_input, row_limit=10, text_limit=2000, list_limit=20)

        dataset_refs = self._normalize_dataset_refs(inputs.get("dataset_ref"))
        if dataset_refs:
            payload["dataset_ref"] = [compact_dataset_ref(item, preview_limit=10) for item in dataset_refs]

        return payload or None

    def execute(self, node: Node, inputs: dict[str, Any], context: object) -> dict[str, Any]:
        sandbox = self._ensure_sandbox()
        container = sandbox.container
        code = self._resolve_code(node)

        safe_id = "".join(ch if str(ch).isalnum() or ch in ("-", "_") else "_" for ch in str(node.id)) or "script"
        script_path = f"/workspace/.workflow_scripts/{safe_id}.py"
        input_payload = self._build_input_payload(node, inputs)

        # Helpers are injected before user code so generated scripts can load dataset_ref
        # inputs without reimplementing per-format readers on every workflow.
        full_code = f"{self._helper_prelude()}\n\n{code}"
        write_cmd = (
            f"mkdir -p /workspace/.workflow_scripts && "
            f"cat > {script_path} <<'PYCODE'\n{full_code}\nPYCODE"
        )
        exit_code, output = container.exec_run(
            cmd=["bash", "-c", write_cmd],
            demux=True,
            workdir="/workspace",
        )
        write_stdout = output[0].decode("utf-8") if output[0] else ""
        write_stderr = output[1].decode("utf-8") if output[1] else ""
        if exit_code != 0:
            raise RuntimeError(write_stderr or write_stdout or "failed to write python code")

        input_data = None
        # Prepare stdin file if payload exists
        input_redirect = ""
        if input_payload is not None:
            input_file = f"/workspace/.workflow_scripts/{safe_id}_input.json"
            input_data = json.dumps(input_payload, ensure_ascii=False, indent=2)
            write_input_cmd = f"cat > {input_file} <<'EOF'\n{input_data}\nEOF"
            exit_code, output = container.exec_run(
                cmd=["bash", "-c", write_input_cmd],
                demux=True,
                workdir="/workspace",
            )
            write_in_stdout = output[0].decode("utf-8") if output[0] else ""
            write_in_stderr = output[1].decode("utf-8") if output[1] else ""
            if exit_code != 0:
                raise RuntimeError(write_in_stderr or write_in_stdout or "failed to write python input")
            input_redirect = f" < {input_file}"

        run_cmd = ["bash", "-c", f"cd /workspace && python {script_path}{input_redirect}"]
        exit_code, output = container.exec_run(
            cmd=run_cmd,
            demux=True,
            workdir="/workspace",
        )
        stdout = output[0].decode("utf-8") if output[0] else ""
        stderr = output[1].decode("utf-8") if output[1] else ""
        if exit_code != 0:
            details = stderr or stdout or f"python.code failed with exit_code={exit_code}"
            if input_data:
                preview_lines = input_data.splitlines()[:10]
                preview = "\n".join(preview_lines)
                details = f"{details}\nINPUT_PREVIEW (first 10 lines):\n{preview}\n"
            else:
                details = f"{details}\nINPUT_PREVIEW: <empty>\n"
            raise RuntimeError(details)
        result: dict[str, Any] = {}
        # Small tabular stdout is materialized into a dataset_ref for downstream workflow nodes.
        try:
            parsed = json.loads(stdout.strip())
            if isinstance(parsed, list) and all(isinstance(x, dict) for x in parsed):
                result.update(
                    build_tabular_node_result(
                        parsed,
                        sandbox=sandbox,
                        source="python.code",
                        name_hint=f"{safe_id}_output_rows",
                    )
                )
            elif is_dataset_ref(parsed):
                result["dataset_ref"] = parsed
        except (json.JSONDecodeError, TypeError):
            pass
        return result


class PythonCodeNode(BaseNode):
    node_type = "python.code"

    @classmethod
    def spec(cls) -> NodeSpec:
        return NodeSpec(
            type=cls.node_type,
            description="Execute custom Python code inside the sandbox. Use this for joins or custom transforms that specialized nodes cannot express cleanly. Downstream logic must only rely on the schema explicitly provided by upstream dataset_ref inputs.",
            params_schema={
                "code": {
                    "type": "string",
                    "required": True,
                    "description": "Python code to run. Helpers are preloaded: `json`, `sys`, `pd`, `load_dataset_ref(ref)`, `load_dataset_refs(data)`, `emit_dataframe(df)`, and `emit_json(value)`. Read stdin with `data = json.load(sys.stdin)`, use `data.get('input')` for small parameters, and load tabular inputs through the helper functions instead of guessing file formats manually. Only reference columns that are explicitly present in the upstream dataset_ref metadata or preview.",
                },
            },
            inputs={
                "input": Port(
                    schema="any",
                    required=False,
                    multiple=True,
                    description="Small JSON-serializable parameters passed to stdin as `data['input']`.",
                ),
                "dataset_ref": Port(
                    schema="dict",
                    required=False,
                    multiple=True,
                    description="Dataset reference(s). Prefer `load_dataset_ref(ref)` or `load_dataset_refs(data)` to read them inside the sandbox.",
                ),
            },
            outputs={
                "dataset_ref": Port(schema="dict", required=False, description="Returned dataset reference when the script materializes tabular output."),
            },
        )

    @classmethod
    def build_handler(cls, db, user_id, sandbox=None):
        return PythonCodeHandler(sandbox)
