import os

import pandas as pd
import pytest

os.environ.setdefault("ALLOW_INSECURE_DEFAULTS", "true")
os.environ.setdefault("LLM_API_KEY", "test-key")
os.environ.setdefault("LLM_BASE_URL", "http://localhost:8000")
os.environ.setdefault("LLM_MODEL", "test-model")

from app.node.video.config.generator import (
    LLMClient,
    calculate_retry_wait_time,
    should_retry_on_error,
)
from app.node.video.config.data_utils import (
    accumulate_token_usage,
    compare_numeric_value,
    dataframe_to_list,
    list_to_dataframe,
)


class _FakeLLMClient(LLMClient):
    def __init__(self, response: str) -> None:
        super().__init__("http://llm.test/v1", "test-key", "test-model")
        self._response = response

    def call(self, *args, **kwargs):
        return self._response, {"prompt_tokens": 1, "completion_tokens": 2, "total_tokens": 3}


def test_retry_policy_treats_quota_errors_as_permanent() -> None:
    should_retry, reason = should_retry_on_error("quota exceeded", attempt=1, elapsed_time=0)

    assert should_retry is False
    assert "永久性错误" in reason


def test_retry_policy_allows_rate_limit_until_time_budget() -> None:
    should_retry, reason = should_retry_on_error("429 rate limit", attempt=5, elapsed_time=60)

    assert should_retry is True
    assert "Rate Limit" in reason
    assert calculate_retry_wait_time("429 rate limit", attempt=5) == 32


def test_retry_policy_stops_context_length_errors() -> None:
    should_retry, reason = should_retry_on_error("maximum context length exceeded", attempt=1, elapsed_time=0)

    assert should_retry is False
    assert "Context length" in reason


def test_retry_policy_caps_general_errors_by_attempt_count() -> None:
    assert should_retry_on_error("temporary upstream failure", attempt=2, elapsed_time=0, max_general_retries=3)[0] is True
    assert should_retry_on_error("temporary upstream failure", attempt=3, elapsed_time=0, max_general_retries=3)[0] is False
    assert calculate_retry_wait_time("temporary upstream failure", attempt=7) == 2


def test_call_with_json_mode_parses_direct_singleton_array() -> None:
    client = _FakeLLMClient('[{"status": "ok"}]')

    parsed, usage = client.call_with_json_mode("prompt", verbose=False)

    assert parsed == {"status": "ok"}
    assert usage == {"prompt_tokens": 1, "completion_tokens": 2, "total_tokens": 3}


def test_call_with_json_mode_extracts_fenced_json_and_repairs_comments_and_trailing_commas() -> None:
    client = _FakeLLMClient(
        """```json
        {
          "title": "Revenue", // generated by LLM
          "values": [1, 2,]
        }
        ```"""
    )

    parsed, _ = client.call_with_json_mode("prompt", verbose=False)

    assert parsed == {"title": "Revenue", "values": [1, 2]}


def test_call_with_json_mode_extracts_embedded_json_and_repairs_control_chars() -> None:
    client = _FakeLLMClient('Here is the JSON: {"message": "hello\nworld"}')

    parsed, _ = client.call_with_json_mode("prompt", verbose=False)

    assert parsed == {"message": "hello\nworld"}


def test_call_with_json_mode_reports_debug_context_when_no_json_object_exists() -> None:
    client = _FakeLLMClient("I could not produce structured output.")

    with pytest.raises(ValueError) as exc_info:
        client.call_with_json_mode("prompt", verbose=False)

    message = str(exc_info.value)
    assert "Cannot parse JSON response" in message
    assert "model=test-model" in message
    assert "--- response_head ---" in message


def test_accumulate_token_usage_adds_known_usage_fields() -> None:
    totals = {"prompt_tokens": 10, "completion_tokens": 20, "total_tokens": 30}

    accumulate_token_usage({"prompt_tokens": 1, "completion_tokens": 2}, totals)
    accumulate_token_usage({"total_tokens": 3}, totals)
    accumulate_token_usage({"prompt_tokens": 99}, None)

    assert totals == {"prompt_tokens": 11, "completion_tokens": 22, "total_tokens": 33}


def test_compare_numeric_value_handles_numeric_strings_and_invalid_values() -> None:
    assert compare_numeric_value("10.5", 10, ">") is True
    assert compare_numeric_value(10, 10, ">=") is True
    assert compare_numeric_value(9.9, 10, "<") is True
    assert compare_numeric_value(None, 10, ">") is False
    assert compare_numeric_value("not-a-number", 10, ">") is False
    assert compare_numeric_value(10, 10, "!=") is False


def test_dataframe_helpers_handle_empty_and_missing_values() -> None:
    assert list_to_dataframe([]).empty is True
    df = list_to_dataframe([{"name": "A", "value": 1}, {"name": "B", "value": pd.NA}])
    assert list(df.columns) == ["name", "value"]

    rows = dataframe_to_list(df)

    assert rows == [{"name": "A", "value": 1}, {"name": "B", "value": None}]
    assert dataframe_to_list(pd.DataFrame()) == []
